export const siteConfig = {
  name: "VisitMyLink",
  url: "https://visitmyl.ink",
  ogImage: "https://ui.shadcn.com/og.jpg",
  description:
    "A simple link shortener.",
  links: {
    twitter: "https://twitter.com/HarjjotSinghh",
    github: "https://github.com/HarjjotSinghh/VisitMyLink",
  },
  keywords: [
    "URL shortener",
    "URL shortening",
    "URL shortener app",
    "URL shortener website",
    "Link shortener",
    "Link shortening",
    "Link shortener app",
    "Link shortener website",
    "VisitMyLink",
    "VisitMyLink app",
    "VisitMyLink website",
    "Shortened link",
    "Shortened URL",
    "Shorten link",
    "Shorten URL",
    "Free link shortener",
    "Free URL shortener",
    "Free link shortening",
    "Free URL shortening",
    "Free link shortener app",
    "Free URL shortener app",
    "Free link shortener website",
    "Free URL shortener website",
    "VisitMyLink URL shortener",
    "VisitMyLink URL shortening",
    "VisitMyLink URL shortener app",
    "VisitMyLink URL shortener website",
    "VisitMyLink link shortener",
    "VisitMyLink link shortening",
    "VisitMyLink link shortener app",
    "VisitMyLink link shortener website",
    "VisitMyLink shortened link",
    "VisitMyLink shortened URL",
    "VisitMyLink shorten link",
    "VisitMyLink shorten URL",
    "visitmyl",
    "visitmylink",
    "visitmyl.ink",
  ],
}

export type SiteConfig = typeof siteConfig